short_name = "tekisasu"
name = "Tekisasu Engine"
major = 4
minor = 3
patch = 1
status = "stable"
module_config = ""
year = 2025
website = "https://dev.tekisasu.com"
docs = "4.3"
tekisasu_release = DEV_TEKISASU_RELEASE
tekisasu_xor_key = "TEK4SAS8"
