short_name = "tekisasu"
name = "Tekisasu Engine"
upstream_major = 4
upstream_minor = 6
upstream_patch = 2
upstream_status = "dev"
major = 2026
minor = 3
patch = 1
status = "stable"
module_config = ""
website = "https://dev.tekisasu.com"
docs = "latest"
