#!/bin/bash

#### String replacements
misc/scripts/rebase_string_tool.sh $(pwd) GDExtensionGodotVersion GDExtensionTekisasuVersion
misc/scripts/rebase_string_tool.sh $(pwd) GDExtensionInterfaceGetGodotVersion GDExtensionInterfaceGetTekisasuVersion
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_AREA_2D_H TEKISASU_AREA_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_AREA_3D_H TEKISASU_AREA_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_AREA_PAIR_2D_H TEKISASU_AREA_PAIR_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_AREA_PAIR_3D_H TEKISASU_AREA_PAIR_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BODY_2D_H TEKISASU_BODY_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BODY_3D_H TEKISASU_BODY_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BODY_DIRECT_STATE_2D_H TEKISASU_BODY_DIRECT_STATE_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BODY_DIRECT_STATE_3D_H TEKISASU_BODY_DIRECT_STATE_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BODY_PAIR_2D_H TEKISASU_BODY_PAIR_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BODY_PAIR_3D_H TEKISASU_BODY_PAIR_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BROAD_PHASE_2D_BVH_H TEKISASU_BROAD_PHASE_2D_BVH_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BROAD_PHASE_2D_H TEKISASU_BROAD_PHASE_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BROAD_PHASE_3D_BVH_H TEKISASU_BROAD_PHASE_3D_BVH_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BROAD_PHASE_3D_H TEKISASU_BROAD_PHASE_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_CLOCK TEKISASU_CLOCK
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_COLLISION_OBJECT_2D_H TEKISASU_COLLISION_OBJECT_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_COLLISION_OBJECT_3D_H TEKISASU_COLLISION_OBJECT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_COLLISION_SOLVER_2D_H TEKISASU_COLLISION_SOLVER_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_COLLISION_SOLVER_2D_SAT_H TEKISASU_COLLISION_SOLVER_2D_SAT_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_COLLISION_SOLVER_3D_H TEKISASU_COLLISION_SOLVER_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_COLLISION_SOLVER_3D_SAT_H TEKISASU_COLLISION_SOLVER_3D_SAT_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_CONE_TWIST_JOINT_3D_H TEKISASU_CONE_TWIST_JOINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_CONSTRAINT_2D_H TEKISASU_CONSTRAINT_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_CONSTRAINT_3D_H TEKISASU_CONSTRAINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_DEBUG_DELTA_SMOOTHER TEKISASU_DEBUG_DELTA_SMOOTHER
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_DLOPEN_MODE TEKISASU_DLOPEN_MODE
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_DOCS_PATTERN TEKISASU_DOCS_PATTERN
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_EDITOR_CUSTOM_FEATURES TEKISASU_EDITOR_CUSTOM_FEATURES
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_EDITOR_STOP_SHORTCUT TEKISASU_EDITOR_STOP_SHORTCUT
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_GENERIC_6DOF_JOINT_3D_H TEKISASU_GENERIC_6DOF_JOINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_HINGE_JOINT_3D_H TEKISASU_HINGE_JOINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_JACOBIAN_ENTRY_3D_H TEKISASU_JACOBIAN_ENTRY_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_JOINTS_2D_H TEKISASU_JOINTS_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_JOINT_3D_H TEKISASU_JOINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_LICENSE_TEXT TEKISASU_LICENSE_TEXT
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_LSP_H TEKISASU_LSP_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_MODULE TEKISASU_MODULE
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_PHYSICS_SERVER_2D_H TEKISASU_PHYSICS_SERVER_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_PHYSICS_SERVER_3D_H TEKISASU_PHYSICS_SERVER_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_PIN_JOINT_3D_H TEKISASU_PIN_JOINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SCRIPT_ENCRYPTION_KEY TEKISASU_SCRIPT_ENCRYPTION_KEY
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SHAPE_3D_H TEKISASU_SHAPE_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SILENCE_ROOT_WARNING TEKISASU_SILENCE_ROOT_WARNING
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SLIDER_JOINT_3D_H TEKISASU_SLIDER_JOINT_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SOFT_BODY_3D_H TEKISASU_SOFT_BODY_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SPACE_2D_H TEKISASU_SPACE_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_SPACE_3D_H TEKISASU_SPACE_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_STEP_2D_H TEKISASU_STEP_2D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_STEP_3D_H TEKISASU_STEP_3D_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_UPDATE_INTERPOLATION_TICK TEKISASU_UPDATE_INTERPOLATION_TICK
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_VERSION TEKISASU_VERSION
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_VULKAN_H TEKISASU_VULKAN_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_WINDOWS_CODESIGN_IDENTITY TEKISASU_WINDOWS_CODESIGN_IDENTITY
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_WINDOWS_CODESIGN_PASSWORD TEKISASU_WINDOWS_CODESIGN_PASSWORD
misc/scripts/rebase_string_tool.sh $(pwd) GodotArea2D TekisasuArea2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotArea2Pair2D TekisasuArea2Pair2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotArea2Pair3D TekisasuArea2Pair3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotArea3D TekisasuArea3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotAreaPair2D TekisasuAreaPair2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotAreaPair3D TekisasuAreaPair3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotAreaSoftBodyPair3D TekisasuAreaSoftBodyPair3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBody2D TekisasuBody2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBody3D TekisasuBody3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBodyContact3D TekisasuBodyContact3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBodyPair2D TekisasuBodyPair2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBodyPair3D TekisasuBodyPair3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBodySoftBodyPair3D TekisasuBodySoftBodyPair3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBoxShape3D TekisasuBoxShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBroadPhase2D TekisasuBroadPhase2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotBroadPhase2DBVH TekisasuBroadPhase2DBVH
misc/scripts/rebase_string_tool.sh $(pwd) GodotBroadPhase3D TekisasuBroadPhase3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCapsuleShape2D TekisasuCapsuleShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCapsuleShape3D TekisasuCapsuleShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCircleShape2D TekisasuCircleShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCollisionObject2D TekisasuCollisionObject2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCollisionObject3D TekisasuCollisionObject3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCollisionSolver2D TekisasuCollisionSolver2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCollisionSolver3D TekisasuCollisionSolver3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConcavePolygonShape3D TekisasuConcavePolygonShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConcaveShape2D TekisasuConcaveShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConcaveShape3D TekisasuConcaveShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConeTwistJoint3D TekisasuConeTwistJoint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConstraint2D TekisasuConstraint2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConstraint3D TekisasuConstraint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConvexPolygonShape2D TekisasuConvexPolygonShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotConvexPolygonShape3D TekisasuConvexPolygonShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotCylinderShape3D TekisasuCylinderShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotDampedSpringJoint2D TekisasuDampedSpringJoint2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotFaceShape3D TekisasuFaceShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotG6DOFRotationalLimitMotor3D TekisasuG6DOFRotationalLimitMotor3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotG6DOFTranslationalLimitMotor3D TekisasuG6DOFTranslationalLimitMotor3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotGeneric6DOFJoint3D TekisasuGeneric6DOFJoint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotGrooveJoint2D TekisasuGrooveJoint2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotHeightMapShape3D TekisasuHeightMapShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotHingeJoint3D TekisasuHingeJoint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotJacobianEntry3D TekisasuJacobianEntry3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotJoint2D TekisasuJoint2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotJoint3D TekisasuJoint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotMotionShape3D TekisasuMotionShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysics2D TekisasuPhysics2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysics3D TekisasuPhysics3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysicsDirectBodyState2D TekisasuPhysicsDirectBodyState2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysicsDirectBodyState3D TekisasuPhysicsDirectBodyState3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysicsDirectSpaceState2D TekisasuPhysicsDirectSpaceState2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysicsDirectSpaceState3D TekisasuPhysicsDirectSpaceState3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysicsServer2D TekisasuPhysicsServer2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPhysicsServer3D TekisasuPhysicsServer3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPinJoint2D TekisasuPinJoint2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotPinJoint3D TekisasuPinJoint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotRectangleShape2D TekisasuRectangleShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSegmentShape2D TekisasuSegmentShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSeparationRayShape2D TekisasuSeparationRayShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSeparationRayShape3D TekisasuSeparationRayShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotShape2D TekisasuShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotShape3D TekisasuShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotShapeOwner2D GodotShapeOwner2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotShapeOwner2D TekisasuShapeOwner2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotShapeOwner3D TekisasuShapeOwner3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSliderJoint3D TekisasuSliderJoint3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSoftBody3D TekisasuSoftBody3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSoftBodyShape3D TekisasuSoftBodyShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSpace2D TekisasuSpace2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSpace3D TekisasuSpace3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotSphereShape3D TekisasuSphereShape3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotStep2D TekisasuStep2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotStep3D TekisasuStep3D
misc/scripts/rebase_string_tool.sh $(pwd) GodotTypeInfo TekisasuTypeInfo
misc/scripts/rebase_string_tool.sh $(pwd) GodotVersionHash TekisasuVersionHash
misc/scripts/rebase_string_tool.sh $(pwd) GodotVersionNumber TekisasuVersionNumber
misc/scripts/rebase_string_tool.sh $(pwd) GodotWorldBoundaryShape2D TekisasuWorldBoundaryShape2D
misc/scripts/rebase_string_tool.sh $(pwd) GodotWorldBoundaryShape3D TekisasuWorldBoundaryShape3D
misc/scripts/rebase_string_tool.sh $(pwd) USTRING_GODOT_H USTRING_TEKISASU_H
misc/scripts/rebase_string_tool.sh $(pwd) get_godot_dir_name get_tekisasu_dir_name
misc/scripts/rebase_string_tool.sh $(pwd) godot_alloc tekisasu_alloc
misc/scripts/rebase_string_tool.sh $(pwd) godot_area_2d.h tekisasu_area_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_area_3d.h tekisasu_area_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_area_pair_2d.h tekisasu_area_pair_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_area_pair_3d.h tekisasu_area_pair_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_body_2d.h tekisasu_body_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_body_3d.h tekisasu_body_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_body_direct_state_2d.h tekisasu_body_direct_state_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_body_direct_state_3d.h tekisasu_body_direct_state_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_body_pair_2d.h tekisasu_body_pair_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_body_pair_3d.h tekisasu_body_pair_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_broad_phase_2d.h tekisasu_broad_phase_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_broad_phase_2d_bvh.h tekisasu_broad_phase_2d_bvh.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_broad_phase_3d.h tekisasu_broad_phase_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_broad_phase_3d_bvh.h tekisasu_broad_phase_3d_bvh.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_close tekisasu_close
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_object_2d.h tekisasu_collision_object_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_object_3d.h tekisasu_collision_object_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_solver_2d.h tekisasu_collision_solver_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_solver_2d_sat.h tekisasu_collision_solver_2d_sat.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_solver_3d.h tekisasu_collision_solver_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_solver_3d_sat.cpp tekisasu_collision_solver_3d_sat.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_collision_solver_3d_sat.h tekisasu_collision_solver_3d_sat.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_cone_twist_joint_3d.cpp tekisasu_cone_twist_joint_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_cone_twist_joint_3d.h tekisasu_cone_twist_joint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_constraint_2d.h tekisasu_constraint_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_constraint_3d.h tekisasu_constraint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_free tekisasu_free
misc/scripts/rebase_string_tool.sh $(pwd) godot_generic_6dof_joint_3d.cpp tekisasu_generic_6dof_joint_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_generic_6dof_joint_3d.h tekisasu_generic_6dof_joint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_hinge_joint_3d.cpp tekisasu_hinge_joint_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_hinge_joint_3d.h tekisasu_hinge_joint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_jacobian_entry_3d.h tekisasu_jacobian_entry_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_joint_3d.h tekisasu_joint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_joints_2d.h tekisasu_joints_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_open tekisasu_open
misc/scripts/rebase_string_tool.sh $(pwd) godot_physics_server_2d.h tekisasu_physics_server_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_physics_server_3d.cpp tekisasu_physics_server_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_physics_server_3d.h tekisasu_physics_server_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_pin_joint_3d.cpp tekisasu_pin_joint_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_pin_joint_3d.h tekisasu_pin_joint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_read tekisasu_read
misc/scripts/rebase_string_tool.sh $(pwd) godot_seek tekisasu_seek
misc/scripts/rebase_string_tool.sh $(pwd) godot_shape_2d.h tekisasu_shape_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_shape_3d.cpp tekisasu_shape_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_shape_3d.h tekisasu_shape_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_singleton tekisasu_singleton
misc/scripts/rebase_string_tool.sh $(pwd) godot_slider_joint_3d.cpp tekisasu_slider_joint_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_slider_joint_3d.h tekisasu_slider_joint_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_soft_body_3d.cpp tekisasu_soft_body_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_soft_body_3d.h tekisasu_soft_body_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_space_2d.h tekisasu_space_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_space_3d.cpp tekisasu_space_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_space_3d.h tekisasu_space_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_step_2d.h tekisasu_step_2d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_step_3d.cpp tekisasu_step_3d.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_step_3d.h tekisasu_step_3d.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_tell tekisasu_tell
misc/scripts/rebase_string_tool.sh $(pwd) godot_testerror tekisasu_testerror
misc/scripts/rebase_string_tool.sh $(pwd) godot_unzip_get_current_file_info tekisasu_unzip_get_current_file_info
misc/scripts/rebase_string_tool.sh $(pwd) godot_unzip_locate_file tekisasu_unzip_locate_file
misc/scripts/rebase_string_tool.sh $(pwd) godot_version tekisasu_version
misc/scripts/rebase_string_tool.sh $(pwd) godot_write tekisasu_write
misc/scripts/rebase_string_tool.sh $(pwd) drivers/vulkan/godot_vulkan.h drivers/vulkan/tekisasu_vulkan.h
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_MODULE_MBEDTLS_CONFIG_H TEKISASU_MODULE_MBEDTLS_CONFIG_H
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_MBEDTLS_INCLUDE_H TEKISASU_MBEDTLS_INCLUDE_H
misc/scripts/rebase_string_tool.sh $(pwd) godot_core_mbedtls_config.h tekisasu_core_mbedtls_config.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_module_mbedtls_config.h tekisasu_module_mbedtls_config.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_core_mbedtls_platform.c tekisasu_core_mbedtls_platform.c
misc/scripts/rebase_string_tool.sh $(pwd) GodotConfiguration TekisasuConfiguration
misc/scripts/rebase_string_tool.sh $(pwd) GodotPlatform TekisasuPlatform
misc/scripts/rebase_string_tool.sh $(pwd) godot_target tekisasu_target
misc/scripts/rebase_string_tool.sh $(pwd) godot_arch tekisasu_arch
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_VERSION_STATUS TEKISASU_VERSION_STATUS
misc/scripts/rebase_string_tool.sh $(pwd) GodotDefineConstants TekisasuDefineConstants
misc/scripts/rebase_string_tool.sh $(pwd) GodotVersionConstants TekisasuVersionConstants
misc/scripts/rebase_string_tool.sh $(pwd) GodotPlatformConstants TekisasuPlatformConstants
misc/scripts/rebase_string_tool.sh $(pwd) GodotSharp TekisasuSharp
misc/scripts/rebase_string_tool.sh $(pwd) GodotTargetPlatform TekisasuTargetPlatform
misc/scripts/rebase_string_tool.sh $(pwd) GodotDefineConstants TekisasuDefineConstants
misc/scripts/rebase_string_tool.sh $(pwd) GodotVersionConstants TekisasuVersionConstants
misc/scripts/rebase_string_tool.sh $(pwd) godot_platform tekisasu_platform
misc/scripts/rebase_string_tool.sh $(pwd) GodotPlugins TekisasuPlugins
misc/scripts/rebase_string_tool.sh $(pwd) PackageVersion_Godot_SourceGenerators PackageVersion_Tekisasu_SourceGenerators
misc/scripts/rebase_string_tool.sh $(pwd) PackageVersion_Godot_NET_Sdk PackageVersion_Tekisasu_NET_Sdk
misc/scripts/rebase_string_tool.sh $(pwd) build_godot_api build_tekisasu_api
misc/scripts/rebase_string_tool.sh $(pwd) GodotFloat64 TekisasuFloat64
misc/scripts/rebase_string_tool.sh $(pwd) Godot.NET.Sdk Tekisasu.NET.Sdk
misc/scripts/rebase_string_tool.sh $(pwd) Godot.SourceGenerators Tekisasu.SourceGenerators
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_REAL_T_IS_DOUBLE TEKISASU_REAL_T_IS_DOUBLE
misc/scripts/rebase_string_tool.sh $(pwd) GodotSdkImportsMicrosoftNetSdk TekisasuSdkImportsMicrosoftNetSdk
misc/scripts/rebase_string_tool.sh $(pwd) PackageVersion_GodotSharp PackageVersion_TekisasuSharp
misc/scripts/rebase_string_tool.sh $(pwd) godot_icall tekisasu_icall
misc/scripts/rebase_string_tool.sh $(pwd) GODOTSHARP_DIRS_H TEKISASUSHARP_DIRS_H
misc/scripts/rebase_string_tool.sh $(pwd) GodotTools TekisasuTools
misc/scripts/rebase_string_tool.sh $(pwd) GODOTSHARP_DEFS_H TEKISASUSHARP_DEFS_H
misc/scripts/rebase_string_tool.sh $(pwd) godotsharp_defs.h tekisasusharp_defs.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_data.json tekisasu_data.json
misc/scripts/rebase_string_tool.sh $(pwd) godot.cpp tekisasu.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot_socket.cpp tekisasu_socket.cpp
misc/scripts/rebase_string_tool.sh $(pwd) godot.h tekisasu.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_ext.h tekisasu_ext.h
misc/scripts/rebase_string_tool.sh $(pwd) godot_linuxbsd tekisasu_linuxbsd
misc/scripts/rebase_string_tool.sh $(pwd) library_godot_webxr library_tekisasu_webxr
misc/scripts/rebase_string_tool.sh $(pwd) library_godot_websocket library_tekisasu_websocket
misc/scripts/rebase_string_tool.sh $(pwd) library_godot_webrtc library_tekisasu_webrtc
misc/scripts/rebase_string_tool.sh $(pwd) godot_update_embree tekisasu_update_embree
misc/scripts/rebase_string_tool.sh $(pwd) godot_navigation_server_2d tekisasu_navigation_server_2d
misc/scripts/rebase_string_tool.sh $(pwd) godot_navigation_server_3d tekisasu_navigation_server_3d
misc/scripts/rebase_string_tool.sh $(pwd) GodotSharp TekisasuSharp
misc/scripts/rebase_string_tool.sh $(pwd) godotsharp tekisasusharp
misc/scripts/rebase_string_tool.sh $(pwd) Godot.Bridge Teksiasu.Bridge
misc/scripts/rebase_string_tool.sh $(pwd) Godot.NativeInterop Tekisasu.NativeInterop
misc/scripts/rebase_string_tool.sh $(pwd) GODOT-INTERNAL TEKISASU-INTERNAL
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_BASE_BRANCH TEKISASU_BASE_BRANCH
misc/scripts/rebase_string_tool.sh $(pwd) GODOT_CPP_BRANCH TEKISASU_CPP_BRANCH
misc/scripts/rebase_string_tool.sh $(pwd) godotcontrollerdb tekisasucontrollerdb


#### Filenames
for file in $(find . -type f | grep -F -v ".github" | grep -F -v ".git" | grep -F -v "GODOT.md" | grep -v "x86_64.obj" | grep -v "x86_64.lib" | grep -v "sconsign5.dblite" | grep -v pycache | grep -v "x86_64.exe" | grep -v "rebase_string_tool.sh" | grep -v "rebase_stringlist.sh" | grep -v "rebase_rename.sh"); do misc/scripts/rebase_rename.sh $file Godot Tekisasu ; done
for file in $(find . -type f | grep -F -v ".github" | grep -F -v ".git" | grep -F -v "GODOT.md" | grep -v "x86_64.obj" | grep -v "x86_64.lib" | grep -v "sconsign5.dblite" | grep -v pycache | grep -v "x86_64.exe" | grep -v "rebase_string_tool.sh" | grep -v "rebase_stringlist.sh" | grep -v "rebase_rename.sh"); do misc/scripts/rebase_rename.sh $file godot tekisasu ; done
for file in $(find . -type f | grep -F -v ".github" | grep -F -v ".git" | grep -F -v "GODOT.md" | grep -F -v "GODOT.md" | grep -v "x86_64.obj" | grep -v "x86_64.lib" | grep -v "sconsign5.dblite" | grep -v pycache | grep -v "x86_64.exe" | grep -v "rebase_string_tool.sh" | grep -v "rebase_stringlist.sh" | grep -v "rebase_rename.sh"); do misc/scripts/rebase_rename.sh $file GODOT TEKISASU ; done


#### Folder Names
for folder in $(find . -type d | grep -F -v ".git" | grep -F -v "GODOT.md" | grep -v "x86_64.obj" | grep -v "x86_64.lib" | grep -v "sconsign5.dblite" | grep -v pycache | grep -v "x86_64.exe" | grep -v "rebase_string_tool.sh" | grep -v "rebase_stringlist.sh" | grep -v "rebase_rename.sh"); do misc/scripts/rebase_rename.sh $folder Godot Tekisasu ; done
for folder in $(find . -type d | grep -F -v ".git" | grep -F -v "GODOT.md" | grep -v "x86_64.obj" | grep -v "x86_64.lib" | grep -v "sconsign5.dblite" | grep -v pycache | grep -v "x86_64.exe" | grep -v "rebase_string_tool.sh" | grep -v "rebase_stringlist.sh" | grep -v "rebase_rename.sh"); do misc/scripts/rebase_rename.sh $folder godot tekisasu ; done
for folder in $(find . -type d | grep -F -v ".git" | grep -F -v "GODOT.md" | grep -v "x86_64.obj" | grep -v "x86_64.lib" | grep -v "sconsign5.dblite" | grep -v pycache | grep -v "x86_64.exe" | grep -v "rebase_string_tool.sh" | grep -v "rebase_stringlist.sh" | grep -v "rebase_rename.sh"); do misc/scripts/rebase_rename.sh $folder GODOT TEKISASU ; done


misc/scripts/rebase_headers.sh $(pwd)